font_family      PragmataPro Mono Liga Regular
bold_font        PragmataPro Mono Liga Bold
italic_font      PragmataPro Mono Liga Italic
bold_italic_font PragmataPro Mono Liga Bold Italic

font_features PragmataProMonoLiga-Regular +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Italic +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Bold +calt +ss02 -ss04 +ss11
font_features PragmataProMonoLiga-BoldItalic +calt +ss02 -ss04 +ss11

font_size 8.5
box_drawing_scale 0.001, 0.3, 0.3, 0.3
adjust_line_height 15
adjust_column_width 0
disable_ligatures never
background_opacity 1.0
draw_minimal_borders yes
window_padding_width 5
cursor_shape block
repaint_delay 0
input_delay 0

cursor              #e4ddca
cursor_text_color   #af5f00
foreground          #616162
background          #fdf6e3
color0              #fdf6e3
color8              #b1aa97
color1              #d63b0c
color9              #d63b0c
color2              #008700
color10             #008700
color3              #c18401
color11             #c18401
color4              #005f87
color12             #005f87
color5              #a11ac9
color13             #a11ac9
color6              #56b6c2
color14             #56b6c2
color7              #fdf6e3
color15             #eee8d5

hide_window_decorations yes
env COLORSCHEME=Solarized
