font_family      PragmataPro Mono Liga Regular
bold_font        PragmataPro Mono Liga Bold
italic_font      PragmataPro Mono Liga Italic
bold_italic_font PragmataPro Mono Liga Bold Italic

font_features PragmataProMonoLiga-Regular +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Italic +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Bold +calt +ss02 -ss04 +ss11
font_features PragmataProMonoLiga-BoldItalic +calt +ss02 -ss04 +ss11

font_size 8.0
box_drawing_scale 0.001, 0.5, 0.5, 0.5
adjust_line_height 10
adjust_column_width 1
disable_ligatures never
background_opacity 1.0
draw_minimal_borders yes
window_padding_width 5
cursor_shape block
cursor_beam_thickness 1.0
repaint_delay 0
input_delay 0

cursor              #d4d4d4
cursor_text_color   #af5f00
foreground          #616162
background          #e9e8ea
color0              #e9e8ea
color8              #9f9f9f
color1              #d63b0c
color9              #d63b0c
color2              #008700
color10             #008700
color3              #c18401
color11             #c18401
color4              #005f87
color12             #005f87
color5              #a11ac9
color13             #a11ac9
color6              #56B6C2
color14             #56B6C2
color7              #e9e8ea
color15             #d4d4d4

hide_window_decorations yes
env COLORSCHEME=Light
