font_family      PragmataPro Mono Liga Regular
bold_font        PragmataPro Mono Liga Bold
italic_font      PragmataPro Mono Liga Italic
bold_italic_font PragmataPro Mono Liga Bold Italic

font_size 12.0
box_drawing_scale 0.001, 0.3, 0.3, 0.3
font_features PragmataProMonoLiga-Regular +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Italic +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Bold +calt +ss02 -ss04 +ss11
font_features PragmataProMonoLiga-BoldItalic +calt +ss02 -ss04 +ss11

adjust_line_height 7
adjust_column_width 0
disable_ligatures never
background_opacity 1.0
draw_minimal_borders yes
window_padding_width 7
cursor_shape block
repaint_delay 0
input_delay 0

cursor               #464c5a
cursor_text_color    #a2b2bc
foreground           #a2b2bc
background           #282c34
color0               #282c34
color8               #546d79
color1               #e06c75
color9               #e06c75
color2               #98c379
color10              #98c379
color3               #e5c07b
color11              #e5c07b
color4               #61afef
color12              #61afef
color5               #c678dd
color13              #c678dd
color6               #56b6c2
color14              #56b6c2
color7               #a2b2bc
color15              #3b4048

close_on_child_death yes
allow_remote_control yes
macos_hide_titlebar yes
macos_show_window_title_in_menubar no
macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_window_resizable yes
macos_thicken_font 0.1
macos_traditional_fullscreen no
macos_show_window_title_in_menubar no
env COLORSCHEME=OneDark
