font_family      PragmataPro Mono Liga Regular
bold_font        PragmataPro Mono Liga Bold
italic_font      PragmataPro Mono Liga Italic
bold_italic_font PragmataPro Mono Liga Bold Italic

font_size 12.0
box_drawing_scale 0.001, 0.3, 0.3, 0.3
font_features PragmataProMonoLiga-Regular +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Italic +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Bold +calt +ss02 -ss04 +ss11
font_features PragmataProMonoLiga-BoldItalic +calt +ss02 -ss04 +ss11

adjust_line_height 7
adjust_column_width 0
disable_ligatures never
background_opacity 1.0
draw_minimal_borders yes
window_padding_width 7
cursor_shape block
repaint_delay 0
input_delay 0

cursor              #272727
cursor_text_color   #de935f
foreground          #a2b2bc
background          #080808
color0              #080808
color8              #414141
color1              #ff5454
color9              #ff5454
color2              #8cc85f
color10             #42cf89
color3              #e3c78a
color11             #cfcfb0
color4              #80a0ff
color12             #78c2ff
color5              #ce76e8
color13             #ae81ff
color6              #7ee0ce
color14             #85dc85
color7              #f74782
color15             #171717

close_on_child_death yes
allow_remote_control yes
macos_hide_titlebar yes
macos_show_window_title_in_menubar no
macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_window_resizable yes
macos_thicken_font 0.1
macos_traditional_fullscreen no
macos_show_window_title_in_menubar no
env COLORSCHEME=Dark
