font_family      PragmataPro Mono Liga Regular
bold_font        PragmataPro Mono Liga Bold
italic_font      PragmataPro Mono Liga Italic
bold_italic_font PragmataPro Mono Liga Bold Italic

font_size 12.0
box_drawing_scale 0.001, 0.3, 0.3, 0.3
font_features PragmataProMonoLiga-Regular +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Italic +calt +ss02 -ss03 +ss11
font_features PragmataProMonoLiga-Bold +calt +ss02 -ss04 +ss11
font_features PragmataProMonoLiga-BoldItalic +calt +ss02 -ss04 +ss11

adjust_line_height 7
adjust_column_width 0
disable_ligatures never
background_opacity 1.0
draw_minimal_borders yes
window_padding_width 7
cursor_shape block
repaint_delay 0
input_delay 0

cursor              #8da3af
cursor_text_color   #212531
foreground          #8da3af
background          #212531
color0              #212531
color8              #3d5b67
color1              #ff566d
color9              #ff566d
color2              #7fab66
color10             #7fab66
color3              #e9b760
color11             #e9b760
color4              #6598ff
color12             #6598ff
color5              #c476ea
color13             #c476ea
color6              #66b5c9
color14             #66b5c9
color7              #8da3af
color15             #22313e

close_on_child_death yes
allow_remote_control yes
macos_hide_titlebar yes
macos_show_window_title_in_menubar no
macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_window_resizable yes
macos_thicken_font 0.1
macos_traditional_fullscreen no
macos_show_window_title_in_menubar no
env COLORSCHEME=Arc
