user: cyan
group: 187
permission:
  read: green
  write: yellow
  exec: red
  exec-sticky: 5
  no-access: dark_grey
  octal: 6
  acl: dark_cyan
  context: cyan
date:
  hour-old: 40
  day-old: 42
  older: 36
size:
  none: 245
  small: 229
  medium: 216
  large: 172
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
